Feature/arrays
KirKozyrev/study pull request #1
Opened 2020-04-20 17:36 UTC by KirKozyrev

2020-04-20 18:04 UTC, artempartos requested changes

2020-04-20 18:04 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max = array.max
нужно реализовать max самому

2020-04-20 18:04 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        for item in array do
в руби не принято обходить массив через for, посмотри на примитивы функционального программирования each, map. reduce

2020-04-20 18:04 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        if _array.length == 0
в руби есть соглашение _ перед переменной означает что переменная не используется, переменуй

2020-04-20 18:04 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        if _array.length == 1 && _array[0] == _query
есть короткая форма записи
`return 0 if _array.length == 1 && _array[0] == _query`

2020-04-20 18:04 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        while arr_start < arr_end do
давай реализуем в рекурсивном стиле

2020-04-21 09:58 UTC, KirKozyrev commented on test/exercise/arrays/solution.rb
> +        max = array.max
Реализовал

2020-04-21 09:58 UTC, KirKozyrev commented on test/exercise/arrays/solution.rb
> +        for item in array do
Поменял for на each

2020-04-21 10:00 UTC, KirKozyrev commented on test/exercise/arrays/solution.rb
> +        if _array.length == 0
Убрал нижнее подчёркивание
P.S. Да, я знаю, что оно значит, но эти переменные были в таком виде изначально (не я их писал), поэтому решил не трогать.

2020-04-21 10:00 UTC, KirKozyrev commented on test/exercise/arrays/solution.rb
> +        if _array.length == 1 && _array[0] == _query
Поменял

2020-04-21 10:01 UTC, KirKozyrev commented on test/exercise/arrays/solution.rb
> +        while arr_start < arr_end do
Реализовал в рекурсивном стиле.

2020-04-21 10:52 UTC, devality approved these changes

2020-04-21 13:22 UTC, merged