Feature/fp
KirKozyrev/study pull request #2
Opened 2020-04-21 13:25 UTC by KirKozyrev

2020-04-23 09:21 UTC, pn-y requested changes

2020-04-23 09:21 UTC, pn-y commented on test/exercise/fp/solution.rb
> +        films_name.each do |film|
Длинно и сложно. Перепиши проще. hint: у строки есть метод `count`

2020-04-23 09:21 UTC, pn-y commented on test/exercise/fp/solution.rb
> +          count_char.push(char_count)
push - семантически относится к стеку. Поэтому вводит в заблуждение. Старайся такого избегать.

2020-04-23 09:21 UTC, pn-y commented on test/exercise/fp/solution.rb
> +            film["rating_kinopoisk"] != nil && film["rating_kinopoisk"].to_f > 0 && film["country"] != nil && film["country"].split(",").length > 1
Чтоб прочитать пришлось даже поскролить. Отформатируй код чтоб его было удобно читать.

2020-04-23 11:01 UTC, devality requested changes

2020-04-23 11:01 UTC, devality commented on test/exercise/fp/solution.rb
> +            (film["rating_kinopoisk"] != nil && film["rating_kinopoisk"].to_f > 0) &&
Есть более изящный способ проверить не нил ли объект, где нет отрицания.

2020-04-23 11:01 UTC, devality commented on test/exercise/fp/solution.rb
> +        rates_sum = films_rates.reduce do |sum, rate|
Такую операцию как сложение аргументов можно выполнить с редьюсом вообще без блока.

2020-04-23 11:01 UTC, devality commented on test/exercise/fp/solution.rb
> +        end
Все тоже самое.

2020-04-25 19:15 UTC, Andrew8xx8 approved these changes

2020-04-26 17:09 UTC, merged